### ISSUE TITLE
Sign Windows CLI executable

### ISSUE THREAD

**Issue by lionello** [DefangLabs/defang#12]
https://learn.microsoft.com/en-us/windows/win32/seccrypto/signtool
https://www.microsoft.com/en-us/wdsi/filesubmission
https://github.com/azure/trusted-signing-action

- [x] create Trusted Signer in Azure portal
- [x] create a Verified Identity in Azure portal
- [x] create a Certificate Policy in Azure portal

The tricky part is that MacOS notarization requires a MacOS runner and Windows signing requires a Windows runner, but both are currently done by GoReleaser, which runs in a single step (on a single runner.) We'll have to split this existing GoReleaser manifest in 2 (or 3) parts so we can have one part done on a MacOS runner and one part done on a Windows runner. See https://github.com/goreleaser/goreleaser-pro-prebuilt-example?tab=readme-ov-file

**Comment by edwardrf** [comment]
Nice to have for Gamma, if the final built triggers windows anti virus

**Comment by lionello** [comment]
Still waiting for completion of the company "Identity Verification" on Azure portal.
