### ISSUE TITLE
Pulumi preview

### ISSUE THREAD

**Issue by raphaeltm** [DefangLabs/defang#123]
Since Defang uses pulumi under the hood to manage stacks, etc. it would be really useful to be able to just run `defang pulumi <pulumi commands>`

**Comment by lionello** [comment]
`defang cd …` works like that for `destroy` and `refresh`. Others like `up` and `preview` would need the Pulumi project files, which is what `defang compose up` creates. What other Pulumi commands are you looking for?

**Comment by lionello** [comment]
`defang cd …` is good enough for now? Missing `preview`.
