### ISSUE TITLE
Deployment says BUILD_QUEUED even though it has failed

### ISSUE THREAD

**Issue by raphaeltm** [DefangLabs/defang#198]

**Comment by lionello** [comment]
@raphaeltm was this Playground or BYOC?

**Comment by raphaeltm** [comment]
Ah shoot. Sorry, I should have recorded that and provided more context. I can't remember at this point. I think I was doing BYOC videos, though, so I think BYOC?

**Comment by lionello** [comment]
Duplicate of #170
