### ISSUE TITLE
Use semantic versioning for the public CD container image

### ISSUE THREAD

**Issue by lionello** [DefangLabs/defang#228]
To ensure that the CLI code expectations match the deployed infra.

**Comment by lionello** [comment]
CLI hardcoded to pick the latest version for a major version number, ie. "v1", "v2" etc.. CD updates would get pushed to the major version, so that older CLIs would not get breaking changes.

**Comment by nullfunc** [comment]
**Description**:

- The public cd is used in BYOC to create and deploy applications.
- Each customer project needs to be built and deployed on to their provider.
- Each project image is tied to a cd version as there may be some resource assignments/configurations or gRPC changes unique to that cd and expected by the application when it was built.
- cd gets updated regularly and may introduce changes which make it incompatible with deployment of already built images

**Use Case**:

- When re-deploying an project without any project source changes we wish to deploy without building and use a cd image with the same major number version as the cd used to build/release the last project image.
- When deploying for the first time or after project source changes the images will be built and deployed with the latest cd

**Work Items:**

- Tag each public cd image with a semver. Keep track of the latest semver and increase minor/patch per update of the cd image
- make each project image contain a cd semver
- update CLI use the latest major version of cd for projects needing rebuild
- update CLI, when deploying an existing project image use the latest non-breaking cd version that the project image was built with
