### ISSUE TITLE
Usability feedback: more user-friendly workflow for staying up-to-date

### ISSUE THREAD

**Issue by beorn** [DefangLabs/defang#238]
Hi,

When using Defang with Pulumi it is a bit tricky to figure out what's going wrong at times — this was my story today:

0. I noticed that my app wasn't working anymore, and after a bit l the docker container running on Defang (not BYOC) was down so my app was failing.  It would be nice to be made aware of this without relying on external healthcheck/monitoring systems, such as sending an email when updates were made to Defang that would make your containers need to be recreated (assuming that was the reason).

2. I tried to re-run `pulumi up` but ran into the below error.  I know I was authenticated before, it would be nice to just tell me that my session had expired and I need to sign in again (that's a bit of a different problem than unauthenticated or using the wrong cluster):
```console
% pulumi up
    error: update failed
  pulumi-nodejs:dynamic:Resource (-app):
    error: 16 UNAUTHENTICATED: invalid token: unknown token KID; wrong Defang cluster?
```

3. I ran `defang login`, and then `pulumi up` again, but then ran into this problem - I guess it would be nice to know how I agree to the terms of service?  Perhaps just tell me in the login window that you popped up and let me agree there?  Perhaps the `defang login` shouldn't even succeed if terms of service and other preconditions weren't met?
```console
% pulumi up
    error: update failed
  pulumi-nodejs:dynamic:Resource (decker-app):
    error: 9 FAILED_PRECONDITION: you must agree to the terms of service first
```

4. Ok I checked the docs and it seems I need to run `defang terms` to see the ToS, so I try that, but that command doesn't exist.  I'm on an old version of the CLI — my defang npm package was updated, but it seems not my cli (maybe could be an idea to make it available via npm too to make this kind of scenario easier).  In any case, I updated it via homebrew.  It seems to be asking me for the ToS twice, but it works.  (Though I wonder if it's enough of a an opt-in to just show the URL and not the whole text?)
```console
% defang terms                                      
 # Using AWS provider
 ! failed_precondition: you must agree to the terms of service first
Our latest terms of service can be found at https://defang.io/terms-service.html
? Do you agree to the Defang terms of service? Yes
 * You have agreed to the Defang terms of service
Our latest terms of service can be found at https://defang.io/terms-service.html
? Do you agree to the Defang terms of service? Yes
 * You have agreed to the Defang terms of service
For help with warnings, check our FAQ at https://docs.defang.io/docs/faq
```

This time it seemed to work.  I guess my ideal workflow would be:

1. Get an email when my container for sure would need to be recreated (instead of letting me find out when my service/app starts failing).
2. Give me an option to have both the defang cli and lib updated through npm so they're always in-sync.
3. In `defang login` also show me the entire ToS if it has changed and ask me to accept it there.
4. In the error messages, tell me more explicitly what to do, e.g.,
  - "failed: session expired — to fix: run `defang login` again"
  - "failed: new Terms of Service — to fix: run `defang login` and accept the Terms of Service there"

**Comment by edwardrf** [comment]
Thanks for your feedback, I'll triage the issues listed here and create individual issues that links back here.
0. There has not been any production deployment, I'll look through to see what caused the container exit
1. We need better error message for expired login from the server side
2. This might be 2 fold:
  a. We need to have a better system of informing the user they have to update their cli
  b. Better server side error message to indicate TOS is needed
3. This again 2 different issues
  a. TOS should not require 2 agrees
  b. better support for NPM: pulumi-defang provider should detect the cli version maybe

I'll create the individual issues and link back here.

**Comment by lionello** [comment]
Better messages tracked by https://github.com/DefangLabs/pulumi-defang/issues/18

**Comment by lionello** [comment]
Closing in favor of #41
