### ISSUE TITLE
npm install -g defang

### ISSUE THREAD

**Issue by raphaeltm** [DefangLabs/defang#322]
I know it's a bit "ouroboros" but I think it would be helpful to be able to do:

```
npx defang install-cli
```

That way someone can test the waters really easily and then if they want to cut down their commands by 4 keystrokes, they can run that once, and they're good to go.

Another advantage is that all our other installation methods either don't work across platforms, require less popular dependencies, or require users to do a bit more work/thinking. Given the relative ubiquity of node (especially with the current target audience) this would just make it easier to install across platforms.

I think the same command could be used to upgrade the CLI as well. (`defang install-cli`)

**Comment by lionello** [comment]
This would also "fix" #310

**Comment by lionello** [comment]
- [ ] `npx defang` should add the resulting binary to `PATH`

**Comment by nullfunc** [comment]
**_npm install -g defang_** will install a link to cli.js which will call the defang binary. The link alias' cli.js and will automatically get the latest version of the defang executable.
