### ISSUE TITLE
Messaging/styling in defang cert gen

### ISSUE THREAD

**Issue by raphaeltm** [DefangLabs/defang#356]
I think it would be helpful to reduce the amount of purple in the output of the `cert gen` command. It's a bit much at the moment and I think it would be best if it were used to highlight the key values. I think most of the text should be white, except something like this:

```
Add the following DNS record:
CNAME
my.really-cool.domain.com
my-cool-service-beta-alb-457881471.us-west-2.elb.amazonaws.com
```

**Comment by lionello** [comment]
Fixed by https://github.com/DefangLabs/defang/pull/392
