### ISSUE TITLE
Update CLI to use new samples json in generate

### ISSUE THREAD

**Issue by raphaeltm** [DefangLabs/defang#402]
We created a new process to publish the samples which publishes them at:
https://docs.defang.io/samples-v2.json

We did this so we could maintain backwards compatibility with the CLI which expected the samples in a different format.

We should migrate the CLI to pull samples from this new format which is more flexible and will remain up to date.

**Comment by raphaeltm** [comment]
@lionello just tagging you in here so have eyes on it

**Comment by lionello** [comment]
Done in #410
