### ISSUE TITLE
Defang Grep (interactive)

### ISSUE THREAD

**Issue by raphaeltm** [DefangLabs/defang#42]
It would be useful to be able to either:

```
defang grep <search>
```

or

```
defang tail --grep <search>
```

Personally I think I tend toward the latter, because I would probably be in the mental context of "I'm looking at logs, actually I need to find something more specific" before I get to grep. It might also be easier because all of the other logic that applies to `tail` should still make sense (i.e. specifying `since`, `etag` etc.)

**Comment by lionello** [comment]
In #459 we want to separate "tail" vs "query". 

I personally would want an interactive grep (press `/` to search)

**Comment by lionello** [comment]
Better to fix #161 and encourage `| grep`
