### ISSUE TITLE
Add Project name as a unique identifier to deployments

### ISSUE THREAD

**Issue by nullfunc** [DefangLabs/defang#437]
Current deployments are identified by tenantId and service name (which is also not unique see [issue 341](https://github.com/DefangLabs/defang-mvp/issues/341). We should add another identifier, **_project_**,  to distinguish between deployments. We should also include this in logs.

**Comment by lionello** [comment]
The protobuf was amended in #464

**Comment by lionello** [comment]
Also see #360 and #73
