### ISSUE TITLE
Reservations warning should mention defaults

### ISSUE THREAD

**Issue by raphaeltm** [DefangLabs/defang#447]
```
WARNING missing memory reservation; specify deploy.resources.reservations.memory to avoid out-of-memory errors 
```

It would be helpful for this warning to specify what values are being set by default.

**Comment by lionello** [comment]
This is hard. The actual minimum depends on the target cloud and on other factors, like the number of CPUs or GPUs (they have implied memory limits.)

I kinda think as soon as we mention a default folks might think the default is fine and leave it as-is, or copy the value and put it in the compose file. Neither is great. You should base this number of other things, like monitoring (which we should add) or calculations.

**Comment by raphaeltm** [comment]
Hmm. I think that's fair. I also think that we should be more explicit, otherwise it's kinda confusing because I know, based on the message, that there must be some value... but I don't know what that value is.

Maybe the message should just specify "based on <cloud-provider>'s defaults" or something.

**Comment by lionello** [comment]
Change the warning message to suggest that provider-specific defaults are being used.
