### ISSUE TITLE
Allow users to "import" infra details as env vars

### ISSUE THREAD

**Issue by raphaeltm** [DefangLabs/defang#451]
In limited cases, it might be useful for a user to "import" details about their infra into a service.

Imagine the following. A user has a service for which there are particular scaling parameters that they understand. If they were able to access the arn for a service for example, they could use the aws sdk to update the task count, or something along those lines.

**Comment by lionello** [comment]
Could be done in a way similar to having secrets as files.

SDK is more interesting path forward.
