### ISSUE TITLE
Managed Service Logs

### ISSUE THREAD

**Issue by raphaeltm** [DefangLabs/defang#454]
Looks like my managed redis instance doesn't produce any logs. It would be nice to get those if possible:

![CleanShot 2024-06-07 at 14 47 13@2x](https://github.com/DefangLabs/defang/assets/910895/a27b4a76-a019-4908-90be-509bb89c51eb)

**Comment by lionello** [comment]
I'm not sure how useful this is. What are we even expecting to see? What's more, Elasticache does have a way to make this work, but MemoryDB does not, and I'd like to make sure we can pick one over the other, eg. based on usage.

**Comment by lionello** [comment]
It is possible, but not trivial. Closing for now.
