### ISSUE TITLE
Status stuck on TASK_STOPPED but service is up and running

### ISSUE THREAD

**Issue by raphaeltm** [DefangLabs/defang#499]
This service was deployed a long time ago and has been up and running consistently, but at some point its status changed to `TASK_STOPPED` and it just stayed that way.

![CleanShot 2024-06-25 at 13 55 43@2x](https://github.com/DefangLabs/defang/assets/910895/7a80f88e-c157-4c06-8103-101b380710a8)

![CleanShot 2024-06-25 at 13 55 53@2x](https://github.com/DefangLabs/defang/assets/910895/b208eebe-122c-45c2-9722-5daa96263f81)

**Comment by nullfunc** [comment]
@raphaeltm might be fixed already with this [PR](https://github.com/DefangLabs/defang-mvp/pull/830)

**Comment by lionello** [comment]
Fixed in 62340dc0c193237a38b9b1759d77a9e52636a871
