### ISSUE TITLE
npx defang@<version> fails to get the version

### ISSUE THREAD

**Issue by nullfunc** [DefangLabs/defang#568]
npx defang@<version> ...
starting with version 0.5.26 we cannot get a specific version.

Reason: the cli.js from 0.5.26 will download the latest version if there is no installed binary regardless of the @version passed to npx. cli.js never gets @version info.

We should add a flag --use-version=<version> (e.g. npx defang <command> --use-version=0.5.26) when we want to use a specific version. 

- The downloaded binary should be tagged (the file could be renamed to include the version info) with the version it is
- cli.js should look for the version installed locally before downloading

**Comment by lionello** [comment]
Also would be useful to add to our shell script installer.

**Comment by lionello** [comment]
Not important enough. Can use the alternative installers instead.
