### ISSUE TITLE
Regression: redeploying on BYOC does not show the link to the project

### ISSUE THREAD

**Issue by Chrisyhjiang** [DefangLabs/defang#579]
Link is not showing up in the BYOC deployment. 
<img width="882" alt="Screenshot 2024-07-25 at 2 06 38 PM" src="https://github.com/user-attachments/assets/2aae9aec-d68b-4062-8318-dbcb3ad100b7">

Image above is when I make a change but do a defang compose up without compose down, the URL is not shown, making it confusing where to go to see if the change is applied. Even after a compose down and a compose up, the link still does not show up.

**Comment by lionello** [comment]
Was fixed by #613
