### ISSUE TITLE
Edit first line of output in CLI

### ISSUE THREAD

**Issue by lionello** [DefangLabs/defang#585]
I just noticed the first line of output in the CLI is this:
`Defang CLI manages services on the Defang cluster`
Can we either delete it or edit it - I don't think we use the term `Defang cluster `anywhere else.

**Comment by jordanstephens** [comment]
@lionello the term "Defang Cluster" appears in the output of `defang -h` as well:

```
defang -h | grep 'Defang cluster'
Defang CLI manages services on the Defang cluster
  login       Authenticate to the Defang cluster
  -s, --cluster string      Defang cluster to connect to (default "fabric-prod1.defang.dev")
```

There is even a `--cluster` switch. Is there another term you would prefer?
