### ISSUE TITLE
BYOC does not support singular host services

### ISSUE THREAD

**Issue by Chrisyhjiang** [DefangLabs/defang#592]
<img width="1240" alt="Screenshot 2024-07-30 at 1 36 54 PM" src="https://github.com/user-attachments/assets/78096b15-815c-4a17-a931-c5c8cab23a01">
BYOC does not support singular host services, but when I switched over to ingress it worked.

**Comment by commit111** [comment]
it works on playground, will test again with byoc

**Comment by commit111** [comment]
singular host service appears to work on byoc now.

**Comment by commit111** [comment]
will close as not reproducible

**Comment by commit111** [comment]
reopened, closed by accident

**Comment by commit111** [comment]
the error shows on BYOC when a user does a compose down, then ctrl+c quickly, and retries a compose up again.

**Comment by commit111** [comment]
closed as not reproducible
