### ISSUE TITLE
Can't switch accounts

### ISSUE THREAD

**Issue by ec-raphael** [DefangLabs/defang#595]
I need to switch to a different Defang account, but when I run `defang logout` if I try to login again, I automatically get logged in with the same GitHub account. I am logged into GitHub with multiple accounts, so my expectation would be that I get to choose the account when I login.

I'm able to get around this by manually copy/pasting the link into an incognito window, but it's not the nicest flow.

**Comment by raphaeltm** [comment]
Nvm. It does work. I guess I got logged out of my other account and didn't realize.
