### ISSUE TITLE
Config values confusing output logging. 

### ISSUE THREAD

**Issue by Chrisyhjiang** [DefangLabs/defang#596]
<img width="1030" alt="Screenshot 2024-07-31 at 4 07 56 PM" src="https://github.com/user-attachments/assets/52675af5-5b6e-4760-9a79-503c095d2f3d">

Note the 2 messages:
service "rag-chatbot": environment variable "OPENAI_API_KEY" overridden by config
The "OPENAI_API_KEY" variable is not set. Defaulting to a blank string.

is confusing when deploying. For context, this is after doing defang config set OPENAI_API_KEY.

**Comment by lionello** [comment]
Yeah, we should clean up the warnings/errors for this. The idea is that `defang config` always overrides environment that was set in the `compose.yaml`, but we should show more than one message for that case (and even then the message could be clearer.)

How is this affected by the interpolation feature? @nullfunc

**Comment by nullfunc** [comment]
"...Defaulting to a blank string." will no longer show since interpolation was implemented.
