### ISSUE TITLE
Out of Memory issue not showing up during deployment. 

### ISSUE THREAD

**Issue by Chrisyhjiang** [DefangLabs/defang#601]
<img width="1276" alt="Screenshot 2024-08-01 at 12 27 14 PM" src="https://github.com/user-attachments/assets/3d21c98c-8845-41f7-b8c2-4b8e6d9dd6c2">

This is not due to the shm_size. There is no logging that said there is not enough memory for the container, but upon further investigation, that seems like it was the problem.

**Comment by ve-varun-sharma** [comment]
Hmm based on the initial warnings in the terminal you may want to add the following code to your Dockerfile.


Dockerfile:
```
 deploy:
      resources:
        reservations:
          memory: 1GB
```


Can you post your Dockerfile code please? This may fix the issue you're running into! You may need to add the following code and tinker with the optimal memory size that you need

**Comment by lionello** [comment]
The debugger now has access to out of memory errors so should give you better hints.
