### ISSUE TITLE
Show more activity during deployments

### ISSUE THREAD

**Issue by Chrisyhjiang** [DefangLabs/defang#602]
I feel like to someone who doesn't want that much detail, a progress bar would help keep the audience engaged.

**Comment by lionello** [comment]
Do you mean during generation or during deployments? Or when?

**Comment by Chrisyhjiang** [comment]
During the deployment, I feel like deployments take a long time and if someone is uninterested in the logs they will have no idea when the deployment has finished. But this could be during generation also, but defang generate is usually pretty quick.

**Comment by lionello** [comment]
Alternatively, a better spinner that shows more activity. See also #56
