### ISSUE TITLE
CLI not detaching after deployment

### ISSUE THREAD

**Issue by raphaeltm** [DefangLabs/defang#659]
I've got a project with a normal service (a Django app) as well as managed Redis and managed Postgres.

When I run `defang compose up` it never detaches, despite the three services being healthy: the django app shows up as green in the portal with`SERVICE_DEPLOYMENT_COMPLETED` and Redis and Postgres both show up with a black circle and `UPDATE_QUEUED`.

**Comment by lionello** [comment]
Happened also in https://github.com/DefangLabs/s.defang.io/actions/runs/10782434867/job/29902537954

**Comment by Prakash-Sundaresan** [comment]
Is this Playground or BYOC @raphaeltm ?
From the reference to Portal, seems like Playground, but then didn't we disable managed Postgres and Redis in Portal?

**Comment by raphaeltm** [comment]
> Is this Playground or BYOC @raphaeltm ?
> From the reference to Portal, seems like Playground, but then didn't we disable managed Postgres and Redis in Portal?

@Prakash-Sundaresan this was before we disabled it.

**Comment by Prakash-Sundaresan** [comment]
Would it still repro is the question...

**Comment by nullfunc** [comment]
Because we can't detect state of managed services, they never makes it to the "COMPLETED" state. May be we should just assume managed services are up and just depend on the completion state of the other services.

**Comment by Prakash-Sundaresan** [comment]
Isn't there an AWS event for RDS deployment complete?

**Comment by raphaeltm** [comment]
If not, there's got to be something we can do to poll? Given that we have the password, etc. we could run something like `pg_isready` (https://www.postgresql.org/docs/current/app-pg-isready.html) until it returns true or a timeout we set. With redis, we can run redis `ping` until we get `pong` back.
