### ISSUE TITLE
Confusing errors in GH Actions re: logs

### ISSUE THREAD

**Issue by raphaeltm** [DefangLabs/defang#722]
```
 * Tailing logs for deployment ID rihcq126ifho ; press Ctrl+C to detach:
 ! Unable to tail logs. Waiting for the deployment to finish.
Error: missing tail permission: token has invalid audience
 ! deployment failed for service "elysia"
Error: Process completed with exit code 7.
```

This is a bit misleading and/or confusing.

Normally, we get:
```
! Unable to tail logs. Waiting for the deployment to finish.
```

This is already a bit confusing. Maybe we can reword to something like:
> Logs are not tailed in CD. Please run `defang tail --since X` to see logs

In this case, something went wrong and the following 3 lines were shown because of the error (normally they aren't shown)

**Comment by lionello** [comment]
Fixed by #755
