### ISSUE TITLE
Cannot install defang using brew 10/16/24

### ISSUE THREAD

**Issue by dayojohn19** [DefangLabs/defang#754]
![Screenshot 2024-10-16 at 9 26 01 AM](https://github.com/user-attachments/assets/59f7edf4-5fcc-47ea-ac8c-6ae9afab7450)

i followed the installation requirements found here
https://docs.defang.io/docs/getting-started/installing

using MacBook M1 Sequoia
already updated xcode

but installing defang still fails my cli is giving me error indicated on the image

**Comment by lionello** [comment]
I double checked the installer works on my M1 Sequoia, so there must be something with your OS/Xcode installation. Did you try the suggested workaround?
```
sudo rm -rf /Library/Developer/CommandLineTools
sudo xcode-select --install
```

**Comment by lionello** [comment]
It seems to work now.
