### ISSUE TITLE
Regression: Tail/Compose Up no longer show hint on Ctrl-C

### ISSUE THREAD

**Issue by lionello** [DefangLabs/defang#790]
BYOC compose up doesn't print service URL

We should make sure it's clear to the users that deployment has completed and print the service URL. Currently they have to go up the logs to try to find it.

**Comment by commit111** [comment]
As of now, it appears that this issue is not reproducible. When I do BYOC compose up, I see this:
With Ctrl-C:
```
 ! Deployment is not finished. Service(s) might not be running.

Detached. The process will keep running.
To continue the logs from where you left off, do:

  ../../../defang/src/cmd/cli/__debug_bin896549281 --provider aws tail --since 2024-10-30T20:36:08.377107Z --etag do0tcm7zzx03

To silence these hints, do: export DEFANG_HIDE_HINTS=1
```
And without Ctrl-C, the service URL shows up (username omitted):
```
 * Service app is in state DEPLOYMENT_COMPLETED and will be available at:
   - https://app--5173.vuejs.<GITHUB_USERNAME>.defang.app
 * Done.
 ```
